SELECT * FROM TB_PRODUTOS AS P LEFT JOIN TB_IMAGENS AS I ON (P.ID_PRODUTO = I.ID_PRODUTO);

SELECT P.ID_PRODUTO, P.PRODUTO, P.VALOR, I.URL_IMAGEM FROM TB_PRODUTOS AS P LEFT JOIN TB_IMAGENS AS I ON (P.ID_PRODUTO = I.ID_PRODUTO);

SELECT P.ID_PRODUTO, P.PRODUTO, P.VALOR, I.URL_IMAGEM FROM TB_PRODUTOS AS P LEFT JOIN TB_IMAGENS AS I ON (P.ID_PRODUTO = I.ID_PRODUTO) WHERE VALOR>600 ORDER BY P.VALOR ASC;