CREATE DATABASE DB_LOJA_VIRTUAL;

create TABLE TB_PRODUTOS (
ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRODUTO VARCHAR(200) NOT NULL,
VALOR FLOAT(8,2)
);

CREATE TABLE TB_DESCRICOES_TECNICAS (
ID_DESCRICAO_TECNICA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT NOT NULL,
DESCRICAO_TECNICA TEXT,
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID_PRODUTO));

CREATE TABLE TB_IMAGENS(
ID_IMAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT NOT NULL,
URL_IMAGEM VARCHAR(200) NOT NULL,
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID_PRODUTO));

CREATE TABLE TB_CLIENTES (
ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
IDADE INT(3) NOT NULL);

CREATE TABLE TB_PEDIDOS(
ID_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTES(ID_CLIENTE),
DATA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE TB_PEDIDOS_PRODUTOS(
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
FOREIGN KEY(ID_PEDIDO) REFERENCES TB_PEDIDOS(ID_PEDIDO),
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID_PRODUTO));
