SELECT * FROM TB_PEDIDOS LEFT JOIN TB_PEDIDOS_PRODUTOS ON (TB_PEDIDOS.ID_PEDIDO = TB_PEDIDOS_PRODUTOS.ID_PEDIDO);

SELECT * FROM TB_PEDIDOS LEFT JOIN TB_PEDIDOS_PRODUTOS ON (TB_PEDIDOS.ID_PEDIDO = TB_PEDIDOS_PRODUTOS.ID_PEDIDO) LEFT JOIN TB_PRODUTOS ON (TB_PEDIDOS_PRODUTOS.ID_PRODUTO = TB_PRODUTOS.ID_PRODUTO);

SELECT * FROM TB_PEDIDOS RIGHT JOIN TB_PEDIDOS_PRODUTOS ON (TB_PEDIDOS.ID_PEDIDO = TB_PEDIDOS_PRODUTOS.ID_PEDIDO) RIGHT JOIN TB_PRODUTOS ON (TB_PEDIDOS_PRODUTOS.ID_PRODUTO = TB_PRODUTOS.ID_PRODUTO);

SELECT * FROM TB_PEDIDOS INNER JOIN TB_PEDIDOS_PRODUTOS ON (TB_PEDIDOS.ID_PEDIDO = TB_PEDIDOS_PRODUTOS.ID_PEDIDO);

SELECT * FROM TB_PEDIDOS INNER JOIN TB_PEDIDOS_PRODUTOS ON (TB_PEDIDOS.ID_PEDIDO = TB_PEDIDOS_PRODUTOS.ID_PEDIDO) INNER JOIN TB_PRODUTOS ON (TB_PEDIDOS_PRODUTOS.ID_PRODUTO = TB_PRODUTOS.ID_PRODUTO);