SELECT * FROM TB_CLIENTES LEFT JOIN TB_PEDIDOS ON (TB_CLIENTES.ID_CLIENTE = TB_PEDIDOS.ID_CLIENTE);

SELECT * FROM TB_PRODUTOS LEFT JOIN TB_IMAGENS ON (TB_PRODUTOS.ID_PRODUTO = TB_IMAGENS.ID_PRODUTO);