SELECT * FROM TB_CLIENTES LEFT JOIN TB_PEDIDOS ON (TB_CLIENTES.ID_CLIENTE = TB_PEDIDOS.ID_CLIENTE);
SELECT * FROM TB_CLIENTES RIGHT JOIN TB_PEDIDOS ON (TB_CLIENTES.ID_CLIENTE = TB_PEDIDOS.ID_CLIENTE);

SELECT * FROM TB_CLIENTES INNER JOIN TB_PEDIDOS ON (TB_CLIENTES.ID_CLIENTE = TB_PEDIDOS.ID_CLIENTE);